# Generated by Django 3.1 on 2020-10-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=50, verbose_name='Nome da Disciplina')),
            ],
            options={
                'verbose_name_plural': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('nome_aluno', models.CharField(max_length=50, verbose_name='Nome do Aluno')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.disciplina')),
            ],
            options={
                'verbose_name_plural': 'Aluno',
            },
        ),
    ]
